CREATE TABLE IF NOT EXISTS "people"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR,
    "surname" VARCHAR,
    "patronymic" VARCHAR DEFAULT '',
    "gender" VARCHAR,
    "age" INTEGER,
    "nationality" VARCHAR,
    UNIQUE ("name", "surname", "patronymic")
);
